BTRX-748 Convert Data Use Restriction View page
broadinstitute/orsp-pub pull request #237
Opened 2019-08-15 18:15 UTC by vvicario

## Addresses
https://broadinstitute.atlassian.net/browse/BTRX-748

## Changes
Remove dataUse/show.gsp and create a new react component 
## Testing
Go to admin -> Data Use Restrictions -> View Restriction.
View restriction page should be displayed properly

---

- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Get a thumb from Belatrix
- [ ] **Submitter**: Get a thumb from @rushtong
- [ ] **Submitter**: Merge to develop using github's "Squash and Merge" feature
- [ ] **Submitter**: Delete branch after merge

2019-08-19 12:01 UTC, rushtong requested changes
See comments inline

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/UrlMappings.groovy
> +        '/api/consent/export'(controller: 'dataUse', action: 'exportConsent', method: 'POST')
Didn't catch this the first time around, but we have two `DataUseController` classes. This is confusing for both developers and for Grails as it tries to do its own wiring based on naming patterns. Having an API version of `DataUseController` introduced this technical debt so we need to be able to track removing the non-API class. Please reference that ticket here (and create it if it doesn't exist) so it's tracked in the PR.

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +    }
nit: add an empty line between methods.

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
>  import groovy.util.logging.Slf4j;
No need for semi-colons, here and at the end of the imports.

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
>  import grails.converters.JSON
This class is missing a package name. Add this at the top of the file:
```
package org.broadinstitute.orsp.api

```

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +    GrailsApplication grailsApplication
This is already in `AuthenticatedController` - there's no need to instantiate another one here that overrides the one in the superclass.

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +        JSON.use(UtilityClass.SAMPLES) {
This is a very confusing closure. As a developer reading this, why would one use `SAMPLES` as a model for rendering a `DataUseRestriction`? Following the code, this makes a little more sense in that it seems to apply only to the `collectionLinks` and not to everything else being rendered. 

Even then, why does `SAMPLES` apply to `collectionLinks`? 

I think the naming here needs to be cleaned up to be more legible.

2019-08-19 12:01 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +                    collectionLinks: samples,
Huh? `collectionLinks` are `samples`?

2019-08-19 12:01 UTC, rushtong commented on grails-app/utils/org/broadinstitute/orsp/utils/UtilityClass.groovy
> +            it.registerObjectMarshaller( ConsentCollectionLink ) { ConsentCollectionLink sc ->
This should be looking at a `SampleCollection`, not a `ConsentCollectionLink`. If the usages of this are passing in a CCL, then that's a category mistake - usages should be passing in a `SampleCollection`.

2019-08-19 12:01 UTC, rushtong commented on package-lock.json
> +{
What happened to this file in feature? Why is it being re-added here? This should be in a separate PR as it is not related to the ticket.

2019-08-19 12:01 UTC, rushtong commented on src/main/webapp/dataUse/DataUseRestrictionDetails.js
> +  }
nit: line break between methods

2019-08-19 12:01 UTC, rushtong commented on src/main/webapp/main/Routes.js
> +import Profile from "../profile/Profile";
nit: We should get in the habit of optimizing imports in JS files which will follow the eslint rules. When you do that, it sorts them appropriately (which actually uses paths, not class names) so we aren't moving lines around for no reason.
```
import React from 'react'
import { Route, Switch } from 'react-router-dom'
import AboutPage from '../aboutPage/AboutPage'
import NewConsentGroup from '../consentGroup/NewConsentGroup'
import DataUseRestrictionDetails from '../dataUse/DataUseRestrictionDetails'
import DataUseRestrictionIndex from '../dataUse/DataUseRestrictionIndex'
import DataUseLetterIndex from '../dataUseLetter/DataUseLetterIndex'
import FundingsSourceReport from '../fundingSourceReport/FundingsSourceReport'
import { LinkWizard } from '../linkWizard/LinkWizard'
import Profile from '../profile/Profile'
import ReviewCategories from '../reviewCategories/ReviewCategories'
import RolesManagement from '../rolesManagement/RolesManagement'
import Main from './Main'

```

2019-08-19 20:32 UTC, vvicario commented on grails-app/controllers/org/broadinstitute/orsp/UrlMappings.groovy
> +        '/api/consent/export'(controller: 'dataUse', action: 'exportConsent', method: 'POST')
I agree, I created story:  https://broadinstitute.atlassian.net/browse/BTRX-765

2019-08-20 12:41 UTC, vvicario commented
@rushtong Please when you have time can you check it? Thanks

2019-08-20 23:42 UTC, rushtong approved these changes
Minor comments inline, but 👍

2019-08-20 23:42 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +                    samples: samples,
nit: alignment - if you want to align the other arguments, this one should be too.

2019-08-20 23:42 UTC, rushtong commented on grails-app/controllers/org/broadinstitute/orsp/api/DataUseController.groovy
> +        }
These two exception cases do the exact same thing. Should be collapsed into a single catch.

2019-08-21 12:44 UTC, tadeork reviewed
:+1:

2019-08-21 12:45 UTC, tadeork approved these changes

2019-08-21 12:52 UTC, merged